name: "🐛 Bug Report"
description: "Something isn't working, an needs to be fixed."
title: ""
labels: ["bug"]
assignees: ["qvgk"]
body:

  - type: input
    id: question1
    attributes:
      label: "What's the problem?"
    validations:
      required: true
